import "./lib/nextFrame";//浏览器兼容下一帧
import { dui,Dui } from "./lib/loadjs";
import { trim,on,off, once, hasClass, getStyle, setStyle, getScrollWidth, addClass, removeClass } from "./lib/dom";
import transition from "./lib/transition";
import watcher from "./lib/watcher";
import { setVnode, setData, bind ,unbind, setProps, convertProp } from "./lib/util";
import { collapseTransition } from "./lib/collapse-transition";
import Popper from "./lib/popper";
import addScroll from "./lib/addScrollBar";//给元素添加自己的滚动条
Dui.prototype.on = on;
Dui.prototype.off = off;
Dui.prototype.trim = trim;
Dui.prototype.once = once;
Dui.prototype.hasClass = hasClass;
Dui.prototype.addClass = addClass;
Dui.prototype.removeClass = removeClass;
Dui.prototype.getStyle = getStyle;
Dui.prototype.setStyle = setStyle;
Dui.prototype.getScrollWidth = getScrollWidth;
Dui.prototype.transition = transition;
Dui.prototype.collapseTransition = collapseTransition;
Dui.prototype.setVnode = setVnode;
Dui.prototype.setData = setData;
Dui.prototype.setProps = setProps;
Dui.prototype.convertProp = convertProp;
Dui.prototype.bind = bind;
Dui.prototype.unbind = unbind;
Dui.prototype.watcher = watcher;
Dui.prototype.popper = Popper;
Dui.prototype.addScroll = addScroll;
export default dui;