import { dui,Dui } from "./lib/loadjs";
import { trim,on,off, once, hasClass, getStyle, setStyle, scrollBarWidth, addClass, removeClass } from "./lib/dom";
import transition from "./lib/transition";
import watcher from "./lib/watcher";
import { setVnode, setData, bind ,unbind, setProps, convertProp, getMaxZIndex } from "./lib/util";
import { collapseTransition } from "./lib/collapse-transition";
import Popper from "./lib/popper";
import addScrollBar from "./lib/addScrollBar";//给元素添加自己的滚动条
import { addResizeListener,removeResizeListener } from "./lib/resize-event";
import addPopper from "./lib/addPopper";
import sort from "./lib/sort";//排序
import JsTree from "./lib/jsTree";
Dui.prototype.on = on;
Dui.prototype.off = off;
Dui.prototype.trim = trim;
Dui.prototype.once = once;
Dui.prototype.hasClass = hasClass;
Dui.prototype.addClass = addClass;
Dui.prototype.removeClass = removeClass;
Dui.prototype.getStyle = getStyle;
Dui.prototype.setStyle = setStyle;
Dui.prototype.getScrollWidth = scrollBarWidth;
Dui.prototype.transition = transition;
Dui.prototype.collapseTransition = collapseTransition;
Dui.prototype.setVnode = setVnode;
Dui.prototype.setData = setData;
Dui.prototype.setProps = setProps;
Dui.prototype.convertProp = convertProp;
Dui.prototype.bind = bind;
Dui.prototype.unbind = unbind;
Dui.prototype.watcher = watcher;
Dui.prototype.popper = Popper;
Dui.prototype.addResizeListener = addResizeListener;
Dui.prototype.removeResizeListener = removeResizeListener;
Dui.prototype.addScrollBar = addScrollBar;
Dui.prototype.getMaxZIndex = getMaxZIndex;
Dui.prototype.addPopper = addPopper;
Dui.prototype.sort = sort;
Dui.prototype.jsTree = JsTree;
export default dui;